# Generated by Django 2.1.3 on 2018-11-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20181126_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
